[tools]
  "aqua:evilmartians/lefthook" = "2.0.3"
  "aqua:nektos/act"            = "0.2.82"
  "aqua:rhysd/actionlint"      = "1.7.8"
  bun                          = '1.3.2'
  node                         = "24.11.0"

[env]
  LEFTHOOK_VERBOSE = "true"
