[tools]
  "aqua:evilmartians/lefthook" = "2.1.0"
  "aqua:nektos/act"            = "0.2.84"
  "aqua:rhysd/actionlint"      = "1.7.10"
  bun                          = '1.3.9'
  node                         = "24.13.0"

[env]
  LEFTHOOK_VERBOSE = "true"
