[tools]
  "aqua:evilmartians/lefthook" = "2.0.11"
  "aqua:nektos/act"            = "0.2.83"
  "aqua:rhysd/actionlint"      = "1.7.9"
  bun                          = '1.3.4'
  node                         = "24.12.0"

[env]
  LEFTHOOK_VERBOSE = "true"
